name: Compare package-sets versions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache PureScript dependencies
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{hashFiles('**/*.dhall')}}-${{hashFiles('package-lock.json')}}
          path: |
            node_modules
            .spago
            output
      - run: npm install
      - run: npm start ${{ secrets.GITHUB_TOKEN }}
