name: Compare package-sets versions

on:
  push:
  schedule:
    - cron: "0 3 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-spago-${{hashFiles('**/*.dhall')}}-${{hashFiles('package-lock.json')}}
          path: |
            node_modules
            .spago
            output
      - run: npm install
      - run: npm run build
      - name: Compare versions
        run: npm start ${{ secrets.GH_TOKEN_CUSTOM }}
